package mybatis.dao;

import mybatis.model.Hotel;
import org.mybatis.cdi.Mapper;

import javax.enterprise.inject.Model;
import java.util.List;

@Mapper
public interface HotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOTEL
     *
     * @mbg.generated Sun Apr 28 18:55:23 EEST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOTEL
     *
     * @mbg.generated Sun Apr 28 18:55:23 EEST 2019
     */
    int insert(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOTEL
     *
     * @mbg.generated Sun Apr 28 18:55:23 EEST 2019
     */
    Hotel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOTEL
     *
     * @mbg.generated Sun Apr 28 18:55:23 EEST 2019
     */
    List<Hotel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOTEL
     *
     * @mbg.generated Sun Apr 28 18:55:23 EEST 2019
     */
    int updateByPrimaryKey(Hotel record);
}