package mybatis.dao;

import mybatis.model.Network;
import org.mybatis.cdi.Mapper;

import javax.enterprise.inject.Model;
import java.util.List;

@Mapper
public interface NetworkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.NETWORK
     *
     * @mbg.generated Sun Apr 28 18:55:23 EEST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.NETWORK
     *
     * @mbg.generated Sun Apr 28 18:55:23 EEST 2019
     */
    int insert(Network record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.NETWORK
     *
     * @mbg.generated Sun Apr 28 18:55:23 EEST 2019
     */
    Network selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.NETWORK
     *
     * @mbg.generated Sun Apr 28 18:55:23 EEST 2019
     */
    List<Network> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.NETWORK
     *
     * @mbg.generated Sun Apr 28 18:55:23 EEST 2019
     */
    int updateByPrimaryKey(Network record);
}