package mybatis.model;

public class Hotel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.HOTEL.ID
     *
     * @mbg.generated Sun Apr 28 18:55:23 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.HOTEL.HOTELNAME
     *
     * @mbg.generated Sun Apr 28 18:55:23 EEST 2019
     */
    private String hotelname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.HOTEL.NETWORK_ID
     *
     * @mbg.generated Sun Apr 28 18:55:23 EEST 2019
     */
    private Integer networkId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.HOTEL.ID
     *
     * @return the value of PUBLIC.HOTEL.ID
     *
     * @mbg.generated Sun Apr 28 18:55:23 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.HOTEL.ID
     *
     * @param id the value for PUBLIC.HOTEL.ID
     *
     * @mbg.generated Sun Apr 28 18:55:23 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.HOTEL.HOTELNAME
     *
     * @return the value of PUBLIC.HOTEL.HOTELNAME
     *
     * @mbg.generated Sun Apr 28 18:55:23 EEST 2019
     */
    public String getHotelname() {
        return hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.HOTEL.HOTELNAME
     *
     * @param hotelname the value for PUBLIC.HOTEL.HOTELNAME
     *
     * @mbg.generated Sun Apr 28 18:55:23 EEST 2019
     */
    public void setHotelname(String hotelname) {
        this.hotelname = hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.HOTEL.NETWORK_ID
     *
     * @return the value of PUBLIC.HOTEL.NETWORK_ID
     *
     * @mbg.generated Sun Apr 28 18:55:23 EEST 2019
     */
    public Integer getNetworkId() {
        return networkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.HOTEL.NETWORK_ID
     *
     * @param networkId the value for PUBLIC.HOTEL.NETWORK_ID
     *
     * @mbg.generated Sun Apr 28 18:55:23 EEST 2019
     */
    public void setNetworkId(Integer networkId) {
        this.networkId = networkId;
    }
}